### ISSUE TITLE
HealthKit.useSubscribeToChanges throw's error on simulator when developing

### ISSUE THREAD

**Issue by walterholohan** [kingstinct/react-native-healthkit#103]
Hey,

Have just run into an issue with using HealthKit.useSubscribeToChanges on a simulator. Its throws the below error when reloading the app during development. Do you know how we could suppress this or is it something that needs fixing?

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/16db7547-d368-4883-9c30-754b7339d67f">

**Comment by walterholohan** [comment]
Ahh ok, might need to not use the hook, as you can't conditionally render a hook

**Comment by walterholohan** [comment]
@robertherber what do you think about updating the hook to something like below i.e. we catch the error and set a flag on the hook so we can know if the subscription was successful or not

```
import { useEffect, useRef, useState } from 'react'

import subscribeToChanges from '../utils/subscribeToChanges'

import type { HKSampleTypeIdentifier } from '..'

function useSubscribeToChanges<TIdentifier extends HKSampleTypeIdentifier>(
  identifier: TIdentifier,
  onChange: () => void,
): boolean {
  const onChangeRef = useRef(onChange)
  const [subscribed, setSubscribed] = useState(false)

  useEffect(() => {
    onChangeRef.current = onChange
  }, [onChange])

  useEffect(() => {
    let cancelSubscription: (() => Promise<boolean>) | undefined

    const init = async () => {
      try {
        cancelSubscription = await subscribeToChanges(identifier, onChangeRef.current)
        setSubscribed(true)
      } catch (error) {
        setSubscribed(false)
      }
      
    }
    void init()

    return () => {
      void cancelSubscription?.()
    }
  }, [identifier])

  return subscribed
}

export default useSubscribeToChanges
```

**Comment by Will-Mann-16** [comment]
I'm getting a similar issue also - would love to see if there's a fix on this. It's only when we are running a local build using the metro bundler that this comes up. I've tried using `react-native-error-boundary` to catch the native exception and it unfortunately hasn't worked.

**Comment by robertherber** [comment]
We're not getting this issue with react-native@0.74.3, expo@51 (old architecture). What are you guys on?

**Comment by Will-Mann-16** [comment]
`react-native@0.74.5` (old architecture) barebones (no expo) - your package version of `8.2.0`

**Comment by Will-Mann-16** [comment]
I managed to replicate it - it was working as intended until I enabled `HealthKit Background Delivery`, happy to share example repo with you if you'd like.
![CleanShot 2024-09-19 at 21 05 10@2x](https://github.com/user-attachments/assets/17c9dcd9-97a2-4cfd-ab69-6c09d210a1ac)

**Comment by robertherber** [comment]
@Will-Mann-16 In that example it looks like you're not requesting permissions for HKWorkoutTypeIdentifier before trying to subscribe to it, so looks like the error makes perfect sense.

**Comment by walterholohan** [comment]
@robertherber yes that is true, however if you want to use the useSubscribe hook in a provider you are unable to conditionally render a hook based on if they have accepted permissions or not.

I guess we have two options

1. handle the error within the hook code instead of letting it be unhandled and polluting the error logs
2. Catch the error on the native side and handle it there i.e. return back an error state in the return type of the function instead of rejecting the promise of the function with an Error

**Comment by robertherber** [comment]
I added a note about it in the [readme](https://github.com/kingstinct/react-native-healthkit/blob/8706c91523c6e5c014192282524233fb0bde6b32/README.md?plain=1#L71).

I think the best is simply to make sure to trigger the hook after the permissions have been requested, I see a few simple options:
1. Render it conditionally (this is how we deal with it). You're right it's not possible if you do it all in the same component by using the hook directly. But if permissions are granted on a different screen (a getting started screen for example) or rendered in a child component that's conditionally rendered (for example a component that is supposed to display the subscribed value) it works.
2. Call subscribeToChange imperatively and implement your own useEffect that waits for permissions to be requested (i.e. "roll your own" hook).

I'm not convinced this should be handled by the library: 
- Just preventing the error will not initiate the subscription after the permissions are requested - we end up with a slight bug instead of an error describing the actual issue.
- Implementing some library-wide state management to keep track of the authorization status - but that would bloat the library.
- Make the hook request permissions if it's not already requested. I agree this would be easier to use initially, but I think this might also end up being more confusing for a developer since a `useSubscribeToChanges` doesn't really imply this is going to happen.
