### ISSUE TITLE
requestAuthorization gives error on newly installed build

### ISSUE THREAD

**Issue by NiklasPainDrainer** [Kingstinct/react-native-healthkit#34]
I'm figuring this is a problem not everybody is having, just me missing a step or so.
I've just installed the package, updated app.json with infoPlist and entitlements.
After opening the app in a dev-build in my physical phone the app crashes immediately when requesting for authorization.

```
import HealthKit, { HKQuantityTypeIdentifier } from "@kingstinct/react-native-healthkit";

const authResult = await HealthKit.requestAuthorization([
	Healthkit.useMostRecentQuantitySample(HKQuantityTypeIdentifier.walkingStepLength),
]);

console.log("authResult: ", authResult);
```

[Image of error showing](https://imgur.com/xFdEb0N)

Got same result when using the examples in readme of package

**Comment by robertherber** [comment]
Are you sure your dev-build is up-to-date?

And just to make sure - the issue is the `Unhandled JS Exception: Unexpected identifier '_reactNativeHealthkit'. Expected ';' after variable declaration. no stack` and not that it's crashing - or is it both?

I noticed in the picture you posted earlier that you have 2 errors logged. It might be interesting to look at the first error as well - maybe it'll give more of a hint.

**Comment by NiklasPainDrainer** [comment]
Managed to get it working. But I don't know why it behaved the way it did. I was reading the requestAuth at my Home screen, which is after a login function. But after changing it to trigger the requestAuth on a button press it was working. It was like React Native has not mounted yet, or something so everything crashed.

**Comment by robertherber** [comment]
Glad you got it working! Let me know if there's anything else 🙂👍
