### ISSUE TITLE
App Store rejection for having references to the Clinical Health Records API without using it.

### ISSUE THREAD

**Issue by WJimmyCook** [Kingstinct/react-native-healthkit#5]
Hi guys,

Thanks for your great work here, react native really needs a good healthkit lib. After I implemented this library into my app and submitted a release Apple rejected the app. 
<img width="890" alt="Screen Shot 2021-01-10 at 7 45 56 AM" src="https://user-images.githubusercontent.com/23268736/104123241-f124b500-5317-11eb-826d-8f1866d3be14.png">

I thought it was because of the example app in this repo (Clinical API permission in the plist) so I removed that from my code and resubmitted it to the app store but it was still rejected. 
<img width="873" alt="Screen Shot 2021-01-10 at 7 51 21 AM" src="https://user-images.githubusercontent.com/23268736/104123334-a6576d00-5318-11eb-96ee-01c1d188e9d5.png">

I'm happy to contribute a PR but I'm not really sure how to go about fixing this (my native iOS knowledge is subpar to say the least) so I would need some direction.

**Comment by robertherber** [comment]
Thanks for letting me know @WJimmyCook! I think this could be a problem for others as well, so I've removed all references to Clinical Records in the newly published v4.0.0. Try resubmitting your app with the new version of this library and it should pass. Good luck with your app! 🚀

For anyone interested in using Clinical Records - use either the old version (3.x, at this time it provides the same functionality) or use the "including-clinical-records" branch.

**Comment by WJimmyCook** [comment]
Awesome thanks! 🚀

**Comment by pruales** [comment]
should clinical records be a separate NPM package?

**Comment by robertherber** [comment]
@pruales Yeah that could work, I think the challenge is maintainability. Right now the branch with clinical records is way outdated. Something along these lines could work:
- main branch -> @kingstinct/react-native-healthkit
- clinical-records branch -> @kingstinct/react-native-healthkit-with-clinical-records

Another potential solution that might be more maintainable (and keep the everything in one package) is somehow making the native code (and config) related to clinical records opt-in, and otherwise not include it in the binary at all. I think this could be possible with an Expo Plugin.
