### ISSUE TITLE
Check Health app installed on device

### ISSUE THREAD

**Issue by ngocht143** [Kingstinct/react-native-healthkit#69]
Hi team,
Is there any way to check if user device installed Health app or not? It's as like as the method

> isAvailable(callback); // Checks is GoogleFit available for current account / installed on device

in react-native-google-fit?
Thanks in advanced.

**Comment by robertherber** [comment]
I think what you're looking for is the [`HealthKit.isHealthDataAvailable()`](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable) method. It checks whether HealthKit is available on the device and whether you can use it.

Not exactly sure what happens if the user uninstalls the Health app - I'm guessing it wouldn't deactivate HealthKit itself. And since the app comes preinstalled on iOS I think it's a rare case. I know on Android the Health Data landscape is a little bit more fragmentet - so I guess whether or not having the Google Fit app installed has a bigger impact on the UX.

Generally to check whether an app is installed you could do the following:
1. Add it's URL Scheme to info.plist (`x-apple-health://` seems to work) [as described here](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl#discussion)
2. Call [`Linking.canOpenUrl("x-apple-health://")`](https://reactnative.dev/docs/linking#canopenurl) to check whether it is installed.

Since the URL scheme to open the Health app is not documented by Apple I think we should avoid adding it to this library, since it runs the risk of getting apps rejected.
